on:
    push:
    pull_request:
    workflow_dispatch:

jobs:
    build:
        runs-on: windows-latest
        strategy:
            matrix:
                proj:
                    - Announcements
                    - Clocks
                    - FakePlayer
                    - UMenu
                    - UMenuEdit
        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-node@v1

            - uses: pnpm/action-setup@v2

            - name: Run pnpm install
              run: pnpm install

            - name: Run npm run auto
              run: npm run auto

            - uses: actions/upload-artifact@v4
              with:
                  name: ${{matrix.proj}}
                  path: |
                      bin/${{matrix.proj}}/
